<?php

namespace App\Filament\Resources\Manufacturers\Pages;

use App\Filament\Resources\Manufacturers\ManufacturerResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateManufacturer extends CreateRecord
{
    protected static string $resource = ManufacturerResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        dd($data);
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
