<?php

namespace App\Filament\Resources\Refunds\Pages;

use App\Filament\Resources\Refunds\RefundResource;
use App\Models\Refund;
use Filament\Actions\Action;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;

class EditRefund extends EditRecord
{
    protected static string $resource = RefundResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Action::make('save')
                ->label('Сохранить')
                ->action(function () {
                    $this->save();
                })
                ->color('primary'),
        ];
    }

    protected function getFormActions(): array
    {
        return [];
    }

    protected function fillForm(): void
    {
        /** @var Refund $date */
        $data = $this->record;

        $data['user_email'] = $data->order->user->email;
        $data['user_phone'] = $data->order->user->client->phone;
        $data['user_client_short_name'] = $data->order->user->client->short_name;

        $data['total_amount'] = $data->total_amount;
        $data['refund_items_count'] = $data->refund_items_count;
        $data['quantity'] = $data->quantity;

        $data['order_shipping_type']    = $data->order_shipping_type_name;
        $data['order_shipping_address'] = $data->order_shipping_address;
        $data['order_is_paid'] = $data->order_is_paid;
        $data['order_created_at'] = $data->order->created_at->format('d.m.Y H:i');
        $data['order_updated_at'] = $data->order->updated_at?->format('d.m.Y H:i');

        parent::fillForm(); // TODO: Change the autogenerated stub
    }
}
