<?php

namespace App\Filament\Resources\Products\Pages;

use App\Filament\Resources\Products\ProductResource;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateProduct extends CreateRecord
{
    protected static string $resource = ProductResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Action::make('save')
                ->label('Создать товар')
                ->action('create')
                ->keyBindings(['mod+s'])
                ->color('primary'),

            Action::make('save_and_create_another')
                ->label('Создать и добавить еще')
                ->action('createAnother')
                ->color('gray')
                ->outlined(),

            Action::make('cancel')
                ->label('Отмена')
                ->url($this->previousUrl ?? static::getResource()::getUrl())
                ->color('gray'),
        ];
    }

    protected function getFormActions(): array
    {
        return [];
    }

    protected function handleRecordCreation(array $data): Model
    {
        dd($data);
//        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
